## **FUNDAMENTOS DE PYTHON**

Escola : Soulcode Academy

Curso: Bootcamp Analista de Dados - Martech - AD2

Professor: Franciane Rodrigues e Douglas Ribeiro

Aluno: Wesley Luiz

* **Lógica de programação:** é um conceito teórico que se refere à forma de pensar e abordar problemas de programação.

* **Algoritmo** é uma descrição abstrata de um processo ou solução que poderá ser executado por um computador;
* **Script** é um conjunto de instruções ou comandos escritos em uma linguagem de programação específica. Geralmente, os scripts são usados para automatizar tarefas ou para definir o comportamento de um programa ou sistema. Eles são frequentemente executados interpretando linha por linha, em vez de serem compilados em um programa executável separado.
* **Programa** é  um conjunto de instruções escritas em uma linguagem de programação específica, organizadas de forma lógica, para realizar uma tarefa ou resolver um problema específico. Ao contrário de um script, um programa é compilado ou interpretado antes da execução, resultando em um arquivo executável que pode ser executado diretamente em um sistema operacional.

## **Comentários e tipos básicos de dados**

In [ ]:
print('Olá, mundo')
print("Olá, mundo")

In [ ]:
# Isto é um comentário

In [ ]:
'''
Isto
é
um
comentário
'''

In [ ]:
"""
Isto
é
um
comentário
"""

In [ ]:
#comentário
#comentário
#comentário

In [ ]:
#Tipos de dados

![Foto 1.png]()

In [ ]:
#Imprimindo alguns dados
print(22) # int
print(1.70) # float
print('Nome') # string aspas simples
print("Sobrenome") # string aspas duplas
print(False) # boolean

**RESUMO**

*   Os **comentários** são como notas que você deixa para que você ou outra pessoa possa ler e ajuda documentar o seu código
*   **Comando print:** é uma função de saída utilizada em várias linguagens de
programação para exibir mensagens ou valores na tela do computador.
*   **\n**: usado para criar quebras de linha em um texto
*   Tipos de dados no Python mais usados são int, float, str, bool
*   int e float: dados quantitativos
*   str: dados categóricos/ qualitativos

## **Variáveis**

In [ ]:
#Declarando as variáveis
idade = 22
altura = 1.70
nome = 'Wesley'
sobrenome = "Luiz"
filhos = False

In [ ]:
# Imprimir na tela usando comando print
print(idade)
print(altura)
print(nome)
print(sobrenome)
print(filhos)

In [ ]:
#Imprimir na tela usando apenas o nome da variável
idade
altura

In [ ]:
# Impressão geral
print(idade, altura)

In [ ]:
# Comando type serve para checarmos o tipo de dado que a variável está declarada
type(idade)

In [ ]:
# Checando o tipo de variável usando os comandos print e type juntos
print(type(idade))
print(type(altura))

In [ ]:
# Atenção: o python é sensivel as letras maiusculas e minusculas
# nome = 'Wesley'
# print(Nome)

In [ ]:
# Armazenando strings e número
nome_completo = 'Wesley Luiz'
numero_favorito = "0"

In [ ]:
# Checando a variável numero_favorito
print(type(numero_favorito))

In [ ]:
# Se o número estiver entre aspas ele se transforma numa string
print(nome_completo, numero_favorito)

In [ ]:
#Primeiro nome do nosso codigo
nome

In [ ]:
# Renomeação da variável
nome = 'Sara'

In [ ]:
# Atualização da variável "nome"
# Sempre a última alterção será a válida
nome

**Resumo**
*  **Variáveis** permitem salvar valores na memória usando um nome que atribuímos
* Declaramos um nome no lado esquerdo do operador igual (“=”), e no lado direito, atribuir o valor que queremos salvar para usar mais tarde.
* Como ler: Declaramos a variável "a" ao valor do "2" do tipo int
* Como ler: Declaramos a variável "b" ao valor do "10.953" do tipo float
* Como ler: A variável "a" recebe valor 2 do tipo int
* Como ler: A variável "b" recebe valor 10.953 do tipo float
* É possível usar os dois comandos print e type juntos
* Atenção: Número pode ser string

**Regras para nomes de variáveis**
* Deve começar com uma letra (maíuscula ou minúscula) ou subcrito(_).
* Nunca pode começar com um número.
* Pode conter letras maiúsculas, minúsculas, números e subscrito.
* Não pode-se utilizar como parte do nome de uma variável:
{ ( + - * / \ ; . , ?)}
* Letras maiúsculas e minúsculas são diferentes:
casa = 4
Casa = 4
*   *Snake Case:* estilo de escrita em que os espaços são substituidos por _, **exemplo**: snake_case
*   *Camel Case:* estilo de escrita em que as palavras são escritas juntas, porém separadas pela inicial maiúscula de cada uma, **exemplo**: camelCase

## **Conversão de variáveis**

In [ ]:
# Conversão de int para float
num_int = 10
num_float = float(num_int)

In [ ]:
# Checando a conversão
print(type(num_int), type(num_float))
print(num_float)

In [ ]:
# Conversão de int para int
num_int = 10
num_str = str(num_int)

In [ ]:
# Checando a conversão
print(type(num_int), type(num_str))
print(num_str)

In [ ]:
# Conversão de float para int
num_float = 10.5
num_int = int(num_float)

In [ ]:
# Checando a conversão
print(type(num_float), type(num_int))
print(num_int)

In [ ]:
# Conversão de float para str
num_float = 10.5
num_str = str(num_float)

In [ ]:
# Checando a conversão
print(type(num_float), type(num_str))
print(num_str)

In [ ]:
# Conversão de str para int
num_str = "10"
num_int = int(num_str)

In [ ]:
# Checando a conversão
print(type(num_str), type(num_int))
print(num_int)

In [ ]:
# Conversão de str para float
num_str = "10.5"
num_float = float(num_str)

In [ ]:
# Checando a conversão
print(type(num_str), type(num_float))
print(num_float)

In [ ]:
# FALHA NO SISTEMA:
#Conversão de str para int ()
# num_str = '10.5'
# num_int = int(num_str)

# Conversão de str para int ()
num_str = '10.5'
num_float = float(num_str) # conversão intermediária
num_int = int(num_float)

# Checando
print(type(num_str), type(num_int))
print(num_int)

## **Operadores Matemáticos**

Os operadores matemáticos básicos, tais como: adição, subtração, multiplicação, divisão, exponenciação e radiciação podem ser feitos dentro do Python.

In [ ]:
# soma (+) Exemplo: some 3 com 2
soma = 3 + 2

# subtração (-) Exemplo: subtraia 2 de 3
sub = 3 - 2

# multiplicação (*) Exemplo: multiplique 3 por 2
mult = 3 * 2

# divisão (/) Exemplo: divida 3 por 2
div = 3 / 2

# parte inteira da divisão (//) Exemplo: encontre e guarde a parte inteira da
# divisão de 3 por 2
idiv = 3 // 2

# resto da divisão (%) Exemplo: encontre e guarde o resto da divisão de 3 por 2
rdiv = 3 % 2

# potenciação (**) Exemplo: eleve 3 a 2
pot = 3 ** 2

print(soma, sub, mult, div, idiv, rdiv, pot)

In [ ]:
# Melhorando a visualização dos prints f-string
print(f'O resultado da soma de 3 com 2 é: {soma}')
print(f'O resultado da subtração de 3 com 2 é: {sub}')
print(f'O resultado da multiplicação de 3 por 2 é: {mult}')
print(f'O resultado da divisão de 3 por 2 é: {div}')
print(f'A parte inteira da divisão de 3 por 2 é: {idiv}')
print(f'O resto da divisão de 3 por 2 é: {rdiv}')
print(f'O resultado da potenciação de 3 elevado a 2 é: {pot}')

In [ ]:
# Adição
n1 = 5.887
n2 = 7.15
soma = n1 + n2
print(soma)
print('A soma é:', round(soma, 2))
print(f"A soma dos números é {soma:.2f}")
print(n1 + n2)
n1+n2

In [ ]:
# Subtração
a1 = 242.5
a2 = 35.4
sub = a1 - a2

# Modos de apresentação
print(sub)
print('A subtração é:', round(sub,2))
print(f"A subtração dos números é {sub:.2f}")
print(a1 - a2)
a1-a2

In [ ]:
# Multiplicação
b1 = 242.5
b2 = 35.4
multi = b1 * b2

# Modos de apresentação
print(multi)
print('A Multiplicação é:', round(multi,2))
print(f"A Multiplicação dos números é {multi:.2f}")
print(b1 * b2)
b1*b2

In [ ]:
# Divisão
x1 = 10
x2 = 5
div = x1/x2

# Modos de apresentação
print(div)
print('A divisão é:', div)
print('A divi é:', round(div,2))
print(f"A divisão dos números é {div:.2f}")
print(x1/x2)
x1/x2

In [ ]:
# parte inteira da divisão (//)

In [ ]:
# resto da divisão (%)

In [ ]:
# potenciação (**)

## **Operadores de comparação (booleanos)**

In [ ]:
# (==) verifica se dois valores são iguais (retorna True ou False)
# Exemplo compare se 3 é igual a 3.0
a = 3 # atribuição do valor 3 (tipo int) para a variável a
b = 3.0 # atribuição do valor 3.0 (tipo float) para a variável b

teste1 = a == b # Fazendo o teste de igualdade de a com b e guradando na variável teste 1
print(teste1) # imprimindo o valor da variável teste1

teste2 = 'wesley' == 'Wesley' # comparando duas strings com uma pequena diferença entre elas
print(teste2) # imprimindo o valor da variável teste2

# (!=) verifica se dois valores são diferentes (retorna True ou False)
# Exemplo: compare se 3 (variável a) é diferente a 3.0 (variável b)
teste3 = a != b
print(teste3)

# (>) verifica se um valor é maior que o outro (retorna True ou False)
# Exemplo: compare se 3 é maior que 2
teste4 = 3 > 2
print(teste4)

# (>=) verifica se um valor é maior ou igual ao outro(Retorna True ou False)
#Exemplo: compare se 3 é maior ou igual a 3
teste5 = 3 >= 3
print(teste5)

# (<) verifica se um número é menor que outro (retorna True ou false)
# Exemplo: compare se 2 é menor que 2
teste6 = 2 < 2
print(teste6)

# (<=) verifica se um valor é menor ou igual ao outro (retorna True ou False)
# Exemplo: compare se 2 é menor ou igual a 2
teste7 = 2 <= 2
print(teste7)

## **Operadores de atribuição**

In [ ]:
# Atribuição direta (=) atribui ao lado esquerdo do sinal um valor que está ao lado direito do sinal
nome = 'douglas'
peso_kg = 78
altura_m = 1.85

# Atribuição de soma (+=), equivale a x = x + y (equivale a uma variável x que já existe recebendo ela mesma + outro valor)
# Exemplo: crie uma variável t que receba o número inteiro 3, e depois some 1 para essa variável
t = 3
t += 1
print(f'O resultado de t + 1 é: {t}')

# Atribuição de subtração (-=) equivale a x = x - y (equivale a uma variável x que já existe recebendo ela mesma - outro valor)
# Exemplo: crie uma variável z que receba o número inteiro 5, e depois diminua 2 para essa variável
z = 5
z -= 2
print(f'O resultado de z - 2 é: {z}')

# atribuição de multiplicação (*=) equivale a x = x * y
# Exemplo: crie uma variável j que receba o número 5, e depois multplique por 2
j = 5
j *= 2
print(f'O resultado de j * 2 é: {j}')

# atribuição de divisão (/=) equivale a x = x / y
# exemplo: crie uma variável w que recebe o número 7, e depois divida por 2
w = 7
w /= 2
print(f'O resultado de w / 2 é: {w}')

# atribuição da parte inteira da divisão (//=) equivale a x = x // y
# Exemplo: crie uma variável k que recebe o número 7, e depois receba a parte inteira da divisão por 2
k = 7
k //= 2
print(f'O resultado de k // 2 é: {k}')

# atribuição do resto da divisão (%=) equivale a x = x % y
# exemplo: crie uma variável b que receba o número 7, e depois receba o resto da divisão dela por 2
b = 7
b %= 2
print(f'O resto  da divisão de b por 2 é: {b}')

# atribuição de potenciação (**=) equivale a x = x ** y
# Exemplo crie uma variável casamento que receba o valor 6 e depois receba o quadrado dela
casamento = 6
casamento **= 2
print(f'O professor douglas casará: {casamento} vezes nesta vida')

## **Operadores Lógicos**

In [ ]:
# (and) Retorna verdadeiro somente se todas as condições de uma comparação forem satisfeitas
# Exemplo:
teste8 = 3 >= 2 and 3 != 2 and 3 < 4
print(f'3 >= 2 and 3 != 2 and 3 < 4 é: {teste8}')
# (&) Retorna verdadeiro somente se todas as condições de uma comparação forem satisfeitas
# Exemplo:
teste9 = (3 <= 2) & (3 != 2) & (3 < 4) #bitwise
#           F           V         V
print(f'(3 <= 2) & (3 != 2) & (3 < 4) é: {teste9}')

# (or) Retorna verdadeiro se pelo menos um dos elementos for verdadeiro
# Exemplo:
teste10 = 3 >= 2 or 3 == 2 or 3 > 4
print(f'3 >= 2 or 3 == 2 or 3 > 43 >= 2 or 3 == 2 or 3 > 4 é: {teste10}')

# (not) Inverte verdadeiro com Falso
# Exemplo:
teste11 = not(teste10)
print(f'not(3 >= 2 or 3 == 2 or 3 > 4) é: {teste11}')
teste12 = not(teste9)
print(f'not((3 <= 2) & (3 != 2) & (3 < 4)) é: {teste12}')
teste13 = ((not(3 <= 2))) & (not(3 == 2)) & (3 < 4) # invertendo o resultado da primeira sentença e da segunda sentença
#               V                 V            V
print(f'((not(3 <= 2))) & (not(3 == 2)) & (3 < 4) é: {teste13}')
teste14 = not((3 >= 2) & (3 != 2) & (3 < 4)) # invertendo o resultado da comparação de todas as sentenças
#                 V         V           V
print(f'not((3 >= 2) & (3 != 2) & (3 < 4)) é: {teste14}')

## **Operadores de identidade (is, is not)**

In [ ]:
# (is) compara se um objeto é igual ao outro em relação ao valor e o tipo
h = 3
p = 3
teste16 = p == h
print(f'p == h é: {teste16}')
teste17 = p is h
print(f'p is h é: {teste17}')
m = 3
n = 3.0
teste18 = m == n
print(f'm == n é: {teste18}')
teste19 = m is n
print(f'm is n é: {teste19}')
print(type(m))
print(type(n))

# (is not) compara se um objeto é diferente do outro em relação ao valor e o tipo
x = 3
y = 4
teste20 = x != y
print(f'x != y é: {teste20}')
teste21 = x is not y
print(f'x is not y é: {teste21}')
o = 3
s = 3.0
teste22 = o != s
print(f'o != s é: {teste22}')
teste23 = o is not s
print(f'o is not s é: {teste23}')
print(type(o))
print(type(s))

## **Operadores de associação**

In [ ]:
# (in) Retorna verdadeiro se um caracter ou sequencia de caracteres for encontrado dentro de uma string
# Exemplo:
nome = 'daniela'
teste24 = 'dani' in nome
print(f'daniela contém dani: {teste24}')
# (not in) Retorna verdadeiro se um caracter ou sequencia de caracteres NÃO for encontrado dentro de uma string
teste25 = 'Dani' not in nome
print(f'daniela não contém Dani: {teste25}')

## **Coletando informações do usuário**

In [ ]:
nome = input('Informe seu nome ')
print(f'O nome digitado é: {nome}')
peso = int(input('Informe seu peso em kg inteiros '))
print(f'{nome} tem : {peso}kg')
altura = float(input('Informe sua altura em metros '))
print(f'{nome} tem {peso} kg e {altura} metros de altura')
imc = peso / altura**2
print(f'{nome}, seu imc é: {imc:.1f}')

## **Strings**

In [ ]:
# 0  1  2  3  4  5  6  7  8   9  10  11  12  13 (índice)
# 1º 2º 3º 4º 5º 6º 7º 8º 9º 10º 11º 12º 13º 14º (ordinal)

email = 'test@gmail.com'
# encontrando um caracter pelo índice

# Exemplo: qual é o quinto caracter dessa string?
print(f'O quinto caracter dessa string é: {email[4]}')
# Exemplo: qual é o último caracter dessa string?
print(f'O último caracter dessa string é: {email[13]}')
# Exemplo: Quais são os caracteres que vem depois do 2º caracter (excluindo o 2º)
print(f'A sequência caracteres dessa string após o segundo é: {email[2:]}')
# Exemplo: Quais são todos os caracteres dessa string?
print(f'A sequência todos os caracteres dessa string é: {email[:]}')
# Exemplo: buscar e imprimir todos os caracteres até o caracter de índice 4 (todos os caracteres antes do @ até o @ incluindo o @)
print(f'A sequência caracteres dessa string até o índice 4 é: {email[:5]}')
# Exemplo como acessar o último caracter da lista sem contar o tamaho dela (sem usar a função len())?
print(f'O último caracter dessa string é: {email[-1]}')

In [ ]:
# SLICING (FATIAMENTO)
# O fatiamento serve para selecionarmos apenas caracteres específicos

fruta = 'morango'
print(fruta[1:]) # a partir do indice 1
print(fruta[:]) # inicio ao fim
print(fruta[:3]) # inicio ate o indice 3 (como o final é excludente ele pega um antes)
print(fruta[1::2]) # do indice 1 pulando de 2 em 2, ate o final
print(fruta[::-1]) # contando de trás pra frente
print(fruta[-1]) # pego o ultimo da posição

# LEN(): contando o tamanho de uma string (len())
print(len(fruta))

## **Método para strings**

In [ ]:
# Sinal de (+) para concatenar strings
nome = 'Wesley'
sobre = 'Luiz'
print(nome +" "+ sobre)
# Converter um número em string
cpf = 12345678910
cpf = str(cpf)
print(type(cpf))

## **Métodos específicos para strings**

In [ ]:
# Declarando a variavel
nome = 'wesley'
print(nome)

# Método para deixar a primeira letra de uma string maiúscula
nome = nome.capitalize()
print(nome)

# Método que deixa tudo em minusculo
nome = nome.casefold()
print(nome)

In [ ]:
# (count) Contar quantas vezes um caracter aparece em uma string
material = 'paralelepípedo'
qtde_p = material.count('p')
print(f'{material} tem {qtde_p} Ps')

In [ ]:
# (endswith) Verifica se uma string termina com um caracter ou sequencia de caracteres
email = 'test@gmail.com'
teste_end = email.endswith('gmail.com')
print(teste_end)

In [ ]:
# (startswith) Verifica se uma string começa com um caracter ou sequencia de caracteres
email = 'test@gmail.com'
teste_beg = email.startswith('d')
print(teste_beg)

In [ ]:
# (isnumeric) Verifica se uma string é formada por números
rg = '123456789'
teste_rg = rg.isnumeric()
print(teste_rg)

In [ ]:
# (isalpha) Verifica se uma string é formada por letras
rg2 = 'test'
teste_rg2 = rg2.isalpha()
print(teste_rg2)

In [ ]:
# (isalnum) Verifica se uma string é formada por letras ou números
rg3 = 'T'
teste_rg3 = rg3.isalnum()
print(teste_rg3)

In [ ]:
# (split) Separa uma string por caracteres específicos, se não for específicado o caracter ela assume espaço como separador
dados = input('informe os valores separados por espaços ')
dados_sep = dados.split()
print(dados_sep)

In [ ]:
# (strip) elimina caracteres indesejados de uma string, por padrão remove espaços do início e do final da string
autor = ' Teste '
print(len(autor))
autor = autor.strip()
print(len(autor))

In [ ]:
# (replace) substitui um caracter por outro
preco = 'R$ 10.50'
print(preco)
preco = preco.replace('.',',')
print(preco)

In [ ]:
# (title) Coloca a primeira letra de cada palavra em maiúscula
comp = 'wesley luiz'
print(comp)
comp = comp.title()
print(comp)

In [ ]:
# (upper) Coloca todas as letras de um texto em maiúsculas
prof = 'wesley'
print(prof)
prof = prof.upper()
print(prof)

## **Estrutura de condição if / elif / else**

Introdução "if":
  *

In [ ]:
'''
  if condição:
    #bloco de codigo a ser executado se a condição for verdadeira
'''

In [ ]:
idade = 22
if idade > 20:
  print('Voce tem mais de 20 anos')

Introdução "else"
  *

In [ ]:
'''
  if condição:
    #bloco de codigo a ser executado se a condição for verdadeira
  else:
    #bloco de codigo a ser executado se a condição nao for verdadeira
'''

In [ ]:
idade = int(input('Digite sua idade: '))

if idade >= 18:
  print('Voce é maior de idade')
else:
  print('Voce é menor de idade')

Introdução "elif"
  * A instrução "elif" é uma abreviação de "else if" e permite testar múltiplas condições em sequência. Ela é usada quando há mais de duas possibilidades a serem consideradas. A sintaxe geral é a seguinte:

In [ ]:
'''
  if condição:
    #bloco de codigo a ser executado se a condição for verdadeira
  elif condição2:
    #bloco de codigo a ser executado se a condição anterior nao for verdadeira e está for verdadeira.
  else:
    #bloco de codigo a ser executado se a condição nao for verdadeira
'''

In [ ]:
nota = float(input('Digite sua nota: '))

if nota >= 90:
  print(f'Sua nota é A: {nota}')
elif nota >= 80:
  print(f'Sua nota é B: {nota}')
elif nota >= 70:
  print(f'Sua nota é c: {nota}')
else:
  print( f'Sua nota é D: {nota}')

Exemplo:
*  Escreva um programa que verifique se um número digitado pelo usuário é positivo, negativo ou zero

Passo a passo:

1. Solicite ao usuário que digite um número.
2. Armazene o número digitado em uma variável chamada "numero".
3. Verifique se o número digitado é igual a zero. Se sim, exiba a mensagem "O número digitado é zero."
4. Caso contrário, verifique se o número é maior que zero. Se sim, exiba a mensagem "O número digitado é positivo."
5. Se nenhuma das condições anteriores for atendida, significa que o número é negativo. Nesse caso, exiba a mensagem "O número digitado é negativo.
6. Encerre o programa.

In [ ]:
numero = float(input("Digite um número: "))

if numero == 0:
    print("O número digitado é zero.")
elif numero > 0:
    print("O número digitado é positivo.")
else:
    print("O número digitado é negativo.")

## **Exercícios de estrutura de condição**

Atividades:
1. Faça um algoritmo que leia um número inteiro e diga se ele é maior, menor ou igual a 10;
2. Faça um algoritmo que leia dois números inteiros e apresente na tela o maior deles ou se eles são iguais;
3. Crie um algoritmo que leia um número e diga se ele está no intervalo fechado entre 25 e 200;
4. Crie um algoritmo que leia um número e informe na tela se o mesmo é positivo. Caso seja, mostre o número na tela;
5. Crie um algoritmo que leia um número e informe se ele é divisível por 7.
6. Crie um algoritmo que leia um número e diga se ele é par ou ímpar.
7. Escreva um programa em Python que solicite ao usuário que digite uma letra. Em seguida, verifique se a letra digitada é uma vogal ou não.
8. Escreva um programa que solicite ao usuário três notas de um aluno e calcule a média. Em seguida, exiba a média e uma mensagem informando se o aluno foi aprovado (média maior ou igual a 7) ou reprovado.
9. Escreva um programa que solicite ao usuário os comprimentos dos três lados de um triângulo. Em seguida, exiba uma mensagem informando se o triângulo é equilátero (todos os lados iguais), isósceles (dois lados iguais) ou escaleno (todos os lados diferentes).
10.  Escreva um programa que solicite ao usuário sua idade e exiba uma mensagem informando em qual faixa etária ele se encontra: criança (0-12 anos), adolescente (13-17 anos), adulto (18-59 anos) ou idoso (60 anos ou mais).

In [ ]:
# Atividade 1
# Faça um algoritmo que leia um número inteiro e diga se ele é maior, menor ou igual a 10;
numero = int(input('Digite um número: '))

if numero == 10:
  print('Numero digitado é igual a 10')
elif numero < 10:
  print('Numero digitado é menor que 10')
else:
  print('Numero digitado é maior que 10')

In [ ]:
# Atividade 2
# Faça um algoritmo que leia dois números inteiros e apresente na tela o maior deles ou se eles são iguais;
numeroUm = int(input('Digite o primeiro número: '))
numeroDois = int(input('Digite o segundo número: '))

if numeroUm > numeroDois:
  print(f'O numero {numeroUm} digitado é maior que {numeroDois}')
elif numeroUm < numeroDois:
  print(f'O numero {numeroDois} digitado é maior que {numeroUm}')
else:
  print(f'Os numeros são iguais')

In [ ]:
# Atividade 3
# Crie um algoritmo que leia um número e diga se ele está no intervalo fechado entre 25 e 200;
numeroIntervalo = float(input('Digite um número: '))

if numeroIntervalo >= 25 and numeroIntervalo <= 200:
  print(f'o número digitado está entre 25 e 200')
else:
  print(f'O número digitado não está entre 25 e 200')

In [ ]:
# Atividade 4
# Crie um algoritmo que leia um número e informe na tela se o mesmo é positivo. Caso seja, mostre o número na tela;
numero4 = int(input('Digite um número: '))

if numero4 > 0:
  print(f'O número digitado ({numero4}) é positivo')
else:
  print(f'O número digitado é negativo')

In [ ]:
# Atividade 5
# Crie um algoritmo que leia um número e informe se ele é divisível por 7.
numero5 = int(input('Digite um número: '))

if numero5 % 7 == 0:
  print(f'O numero {numero5} é divisivel por 7')
else:
  print(f'Não é divisivel por 7')

In [ ]:
# Atividade 6
# Crie um algoritmo que leia um número e diga se ele é par ou ímpar.
numero6 = int(input('Digite um número: '))

if numero6 % 2 == 0:
  print('O numero é par')
else:
  print('O número é impar')

In [ ]:
# Atividade 7
# Escreva um programa em Python que solicite ao usuário que digite uma letra. Em seguida, verifique se a letra digitada é uma vogal ou não.
letra = input('Digite uma letra: ')

vogaisMaiusculas = ["A", "E", "I", "O", "U"]
vogaisMinusculas = ["a", "e", "i", "o", "u"]

if letra in vogaisMaiusculas:
  print(f'A letra digitada é uma vogal')
elif letra in vogaisMinusculas:
  print(f'A letra digitada é uma vogal')
elif letra.isnumeric:
  print(f'Não foi digitado uma letra')
else:
  print(f'A letra digitada é uma consoante')

In [ ]:
# Atividade 8
# Escreva um programa que solicite ao usuário três notas de um aluno e calcule
# a média. Em seguida, exiba a média e uma mensagem informando se o aluno foi aprovado (média maior ou igual a 7) ou reprovado.
nota1 = float(input('Informe a primeira nota: '))
nota2 = float(input('Informe a segunda nota: '))
nota3 = float(input('Informe a terceira nota: '))
media = (nota1 + nota2 + nota3) / 3
if media >= 7:
  print(f'Aprovado com média {media:.2f}')
else:
  print(f'Reprovado com média {media:.2f}')

In [ ]:
# Atividade 9
l1 = float(input('Informe o comprimento do 1º lado: '))
l2 = float(input('Informe o comprimento do 2º lado: '))
l3 = float(input('Informe o comprimento do 3º lado: '))

if l1 < (l2 + l3) and l2 < (l1 + l3) and l3 < (l2 + l1):
  tri = True
else:
  tri = False

if tri == True:
  print('A medidas informadas formam um triangulo')
else:
  print('''A medidas informadas não formam um triangulo, por favor digite
  medidas que formem um triângulo, lembrando que para que exista um triângulo
  a medida de um lado qualquer deve ser menor que a soma das medidas dos outros
  dois lados informado''')

# Código para caso as medidas formem um triangulo,faça sua classificação
if tri == True:
  if l1 == l2 and l2 == l3:
    print('O triângulo é equilátero, tem três lados iguais.')

  elif (l1 == l2 or l1 == l3 or l2 == l3): # and (l1 != l2 or l1 != l3 or l2 != l3): essa condição seria necessária caso não houvesse outra condicação antes dela que pegasse o caso de todos os lados iguais
    print('O triângulo é isósceles, tem dois lados iguais..')

  else:
    print('O triângulo é escaleno todos os lados diferentes.')
else:
  pass

In [ ]:
# Ex 10
age = int(input('Informe a sua idade em anos inteiros: '))
if 0 <= age <= 12: #( se 0 for menor ou igual a age e age for menor ou igual a 12)
  print('criança')
elif 13 <= age <= 17:
  print('adolescente')
elif 18 <= age <= 59:
  print('adulto')
else:
  print('idoso')

In [ ]:
# EX 10
age = int(input('Informe a sua idade em anos inteiros: '))
if age <= 12: #( se 0 for menor ou igual a age e age for menor ou igual a 12)
  print('criança')
elif age <= 17:
  print('adolescente')
elif age <= 59:
  print('adulto')
else:
  print('idoso')

In [ ]:
cadeAlmoco = input("Digite se ja rolou o break ")
nao = ["Não", 'não', 'nao', 'Nao', 'NAO', 'NÃO']
sim = ['Sim','SIM','sim']
if cadeAlmoco == nao:
  print('Cade o break do almoço professor')
elif cadeAlmoco == sim:
  print('Bora almoçar, Bom almoço a todos!')
else:
  print('Digite só sim ou nao')

## **Estruturas de dados - Listas/Arrays**

In [ ]:
# criando uma lista com strings
nomes = ['Wesley', 'Lucas', 'Joao', 'Maria', 'Eduardo', 'Ester']

# criando uma lista com números inteiros
pesos = [78, 25, 98, 63, 92, 67]

# criando uma lista com números fracionários
alturas = [1.85, 1.29, 1.75, 1.67, 1.82, 1.70]

In [ ]:
# forçando um erro usando o remove
# nomes.remove('xerox')

In [ ]:
# solução 1
teste = input('Informe o nome que deseja excluir da lista: ') # recebe um nome do usuário e o guarda na variável teste
teste = teste.capitalize() # Padroniza a variável teste com a primeira letra maiúscula
if teste in nomes: # verifica se o nome armazenado em teste está na lista de nomes
  nomes.remove(teste) # se somente se o nome armazenado em teste estiver na lista, faz a exclusão
  print(f'O nome {teste} foi exluído com sucesso') # imprime o resultado da exclusão se somente se ela for feita
else:
  print(f'O nome {teste} não está na lista, logo não pode ser excluído') # Caso o nome digitado não esteja na lista informa o usuário essa situação

In [ ]:
# solução 2 (utlizando try/except)
teste2 = input('Informe o nome que deseja excluir da lista: ') # recebe um nome do usuário e o guarda na variável teste
teste2 = teste2.capitalize()# Padroniza a variável teste com a primeira letra maiúscula
try: # comando para tentar fazer alguma ação
  nomes.remove(teste2) # ação que será feita caso a tentativa seja bem sucedida (neste caso se o nome digitado estiver na lista)
  print(f'O nome {teste2} foi excluído com sucesso') # imprime o resultado da exclusão se somente se ela for feita
except: # comando para o caso da tentativa (try) ser mal sucedida (no caso se o nome não estiver na lista)
  print(f'O nome {teste2} não está na lista, logo não pode ser excluído') # Caso o nome digitado não esteja na lista informa o usuário essa situação

In [ ]:
# Tamanho da lista len(lista)
print(len(nomes))

# Maior valor da lista
print(max(pesos))

# Menor valor da lista
print(min(alturas))

# Soma dos valores de uma lista
print(sum(alturas))

# Contando a frequência de um valor em uma lista
print(nomes.count('Wesley'))

# Ordenar uma lista crescente
nomes.sort()
print(nomes)
# Ordenar uma lista crescente
nomes.sort(reverse=True)
print(nomes)

In [ ]:
# Adicionando todos os elementos de uma lista em outra usando o método extend
# Melhor para alteração no banco de dados
nomes1 = ['Zé', 'Mané']
nomes2 = ['Ana', 'José']

nomes1.extend(nomes2)

print(nomes1)

In [ ]:
# Adicionando todos os elementos de uma lista em outra usando sinal de (+) (concatenando listas)
# Melhor para filtro
nomes1 = ['Zé', 'Mané']
nomes2 = ['Ana', 'José']

teste = nomes1 + nomes2
print(teste)

In [ ]:
# Colocando uma lista dentro de outra
carros = ['Fusca', 'Gol']
carros2 = ['Uno', 'Punto', 'Bravo']
carros.append(carros2)
print(carros)

In [ ]:
# tirando uma lista da outra
fiat = carros[2]
print(fiat)

In [ ]:
# tirando um item de uma lista que está dentro de outra
ok = carros[2][0]
print(f'O melhor carro de todos os tempos é {ok}')

In [ ]:
# Lista é uma estrutura que pode armazenar diversos valores sobre um determinado atributo
lista_vazia = []
noivo = ['Zé','Mané','Ana','Fran','João','Franz']
print(f'Convidados do noivo - {noivo}')
idades = [41, 47, 46, 28, 17, 50]
print(f'Idades dos convidados do noivo {idades}')
massas = [86, 74, 52, 47, 90, 110]
print(f'Massas dos convidados do noivo {massas}')
alturas = [1.68, 1.74, 1.65, 1.65, 1.80, 1.97]
print(f'Alturas (em metros) dos convidados do noivo {alturas}')

In [ ]:
print(f'Idades dos convidados do noivo {idades}')

In [ ]:
# Acessando um elemento específico da lista a partir do seu índice
print(f'A convidada de honra é {noivo[3]}')
# Criar uma sublista com apenas os os três primeiros elementos da lita noivo
sublista = noivo[:3]
print(sublista)
p_u = [noivo[0], noivo[-1]]
print(f'O primeiro convidado é {p_u[0]} e o último convidado é {p_u[-1]}')
print(f'{noivo}')

In [ ]:
# Método index(valor procurado, índice de ínicio da procura, e índice fim da procura) por definição se não for oferecido o índice de ínicio e fim será procurado na lista toda
id = noivo.index('Fran')

In [ ]:
# Qual é o imc da convidada Fran
print(f'O IMC da Fran é {(massas[id]/alturas[id]**2):.2f}')

Desafio 1':
Crie um programa que receba do usuário um nome e caso esse nome
esteja na lista guarde seu índice em uma variável e a utilize para buscar massa e altura correspondente, bem como calcular seu imc e após tudo isso informar o usuário, caso o nome não esteja na lista retorne uma mensagem informando o usuário

In [ ]:
# Exercicio fixação, que eu fiz
# receber nome, se o nome tiver na lista, guardar indice , peso, altura e calcular imc, fazer print com nome tem tantos quilos e imc se nao estiver "desculpe nao esta no nosso banco de dados tente novamente"
convidadoNome = input('Digite o nome do convidado: ')

nomeId = noivo.index('Mané')
massaCorporal = massas[nomeId]
altura = alturas[nomeId]

if convidadoNome != 'Mané':
  print('Desculpe este nome nao esta no nosso banco de dados, tente novamente!')
else:
  print(f'O nome do convidado é {convidadoNome}, tem {massaCorporal}Kgs e o resultado de seu IMC é igual a {(massas[nomeId]/alturas[nomeId]**2):.2f}')

In [ ]:
# Professor resposta
noivo = ['Zé','Mané','Ana','Fran','João','Franz'] # Cria o banco de dados com os nomes dos convidados do noivo
nome = input('Informe o nome que deseja consultar: ') #recebendo o nome do usuário
nome = nome.capitalize() #Deixo o nome que o usuário digitou com a primeira letra em caixa alta e as demais em caixa baixa
if nome in noivo: # se o nome que o usuário digitou estiver no banco de dados faça algo
  id2 = noivo.index(nome) # recebendo o argumento nome e procurando o seu índice já sabendo que ele está na lista exatmente com a mesma grafia
  imc = massas[id2]/alturas[id2]**2 # calculando o imc já sabendo a posição que deve busta em cada lista (massas e alturas)
  print(f'{nome} tem {massas[id2]} kg, {alturas[id2]} metros e seu imc é: {imc:.1f}') # Mostrando o nome digitado e seus respectivos massa, altura e imc
else:
  print(f'Desculpe, {nome} não está na lista, por favor reinicie o programa para consultar outro nome')

In [ ]:
d = []
d.append(22)
print(d)

In [ ]:
# Adicionando elementos em uma lista qualquer com o método append() por padrão este método insero o valor desejado em uma lista existente na última posição
lista_vazia = [] # cria uma lista vazia com o nome lista vazia e apaga todos os elementos de qualquer objeto com o mesmo nome
print(lista_vazia) # imprime uma lista vazia que já existe
lista_vazia.append('Joana') # adiciona Joana na última posição de uma lista que já exista
lista_vazia.append('Douglas')
lista_vazia.append('Eduardo')
lista_vazia.append('Ester')
lista_vazia.append('Daniela')
lista_vazia.append('Pedro')
lista_vazia.append('Maria')
print(lista_vazia) # imprime o status atual da lista vazia
fam = lista_vazia
print(lista_vazia)
print(fam)

In [ ]:
fam.insert(3, 'Tobias')
print(fam)

In [ ]:
fam[3] = 'Raimundo' # Atribuição direta insere um novo elemento substituindo o anterior se houver
print(fam)

In [ ]:
# Excluindo elementos de uma lista
fam.pop() # método que exclui pelo índice, por padrão exclui o último elemento se não informarmos o índice
print(fam)

In [ ]:
# Excluir Joana da lista fam pelo método pop
fam.pop(0)
print(fam)

In [ ]:
# Excluir raimundo da lista fam pelo método remove
fam.remove('Raimundo')
print(fam)

## Estruturas de repetição (For)

In [ ]:
# Apresentando e utilizando o for de forma simples
pesos = [78, 25, 98, 63, 92, 67]
for peso in pesos:
  print(peso)

In [ ]:
# Utilizando o for com else
for i in pesos:
    print(i)
else:
    print('Todos os items foram exibidos com sucesso')

In [ ]:
notas = [5, 9, 6, 8, 7]
for i in notas:
  print(i)

Função enumerate

In [ ]:
notas = [5, 9, 6, 8, 7]

for i, v in enumerate(notas):
  print(i,v)

In [ ]:
notas = [5, 9, 6, 8, 7] # Recebe uma lista com várias notas
# Objetivo: percorrer toda a lista de notas e para cada valor encontrado testar se o mesmo é ou não maior ou igual a 7
# Se verdadeiro imprima a mensagem aprovado e sua nota
# Se falso imprima reprovado e sua nota
for i, v in enumerate(notas): # primeira variável é o índice e a segunda variável é o valor
  if notas[i] >= 7: # se uma nota qualquer encontrada for maio ou igual a 7 faça algo
    print(f'aprovado com nota {notas[i]}') # se verdadeiro imprima aprovado e sua nota
  else:
    print(f'reprovado com nota {notas[i]}') # se não for verdadeiro imprima reprovado e sua nota
  print(notas[i])

In [ ]:
notas[0]

In [ ]:
# Utilizando o for com range
alturas_quad = []
imc = []
for i in range(5):
  print(i)
  alturas_quad.append(alturas[i]**2)
  imc.append(pesos[i]/alturas_quad[i])
print(f'IMC {imc}')

In [ ]:
# Utilizando o for com enumerate
alturas_quad = []
imc = []
for i, v in enumerate(pesos):
  print(i)
  print(v)
  alturas_quad.append(alturas[i]**2)
  imc.append(pesos[i]/alturas_quad[i])
print(f'IMC {imc}')

## **Estrutura de repetição - While**

Loop While

In [ ]:
66c = 0
n = int(input('Informe quantas vezes deseja ver a mensagem "Hello World": '))
while c < n:
  print('Hello World')
  c += 1
'''
Assim podemos concluir que o while é uma sentença que declara uma condição que
enquanto for verdadeira executa repetidamente um bloco de códigos na linha
por linha na ordem especificada de cada linha
'''

In [ ]:
'''
Faça um script que receba do usuário cinco números inteiros, armazene os
números recebidos em uma lista e no final exiba a soma desses valores
'''
n1 = int(input('Informe o 1º número inteiro: '))
n2 = int(input('Informe o 2º número inteiro: '))
n3 = int(input('Informe o 3º número inteiro: '))
n4 = int(input('Informe o 4º número inteiro: '))
n5 = int(input('Informe o 5º número inteiro: '))
numeros = [n1, n2, n3, n4, n5]
print(f'A soma dos números digitados é: {sum(numeros)} ')

In [ ]:
'''
Faça um script que receba do usuário cinco números inteiros, armazene os
números recebidos a cada momento em que forem recebidos em uma lista e
no final exiba a soma desses valores
'''
numeros = []
n1 = int(input('Informe o 1º número inteiro: '))
numeros.append(n1)
n2 = int(input('Informe o 2º número inteiro: '))
numeros.append(n2)
n3 = int(input('Informe o 3º número inteiro: '))
numeros.append(n3)
n4 = int(input('Informe o 4º número inteiro: '))
numeros.append(n4)
n5 = int(input('Informe o 5º número inteiro: '))
numeros.append(n5)

print(f'A soma dos números digitados é: {sum(numeros)} ')

In [ ]:
'''
Faça um script que receba do usuário n números inteiros, armazene os
números recebidos a cada momento em que forem recebidos em uma lista e
no final exiba a soma desses valores. Considere que o usuário deverá informar
apenas 1 numero inteiro por caixa de diálogo é permitido usar (While)
'''
c = 0 # criei um contador para utilizar como parada do laço while
n = int(input('Informe a qtde de números inteiros que deseja na lista: '))
numeros = []
while c < n:
  numeros.append(int(input(f'Informe o {c+1}º número inteiro da lista: ')))
  c += 1
print(f'A soma dos valores digitados é {sum(numeros)}')

In [ ]:
'''
Faça um script que receba do usuário n números inteiros, armazene os
números recebidos a cada momento em que forem recebidos em uma lista e
no final exiba a soma desses valores. Considere que o usuário deverá informar
apenas 1 numero inteiro por caixa de diálogo é permitido usar (While)
'''
c = 0 # criei um contador para utilizar como parada do laço while
n = int(input('Informe a qtde de números inteiros que deseja na lista: '))
numeros = []
while c < n:
  i = int(input(f'Informe o {c+1}º número inteiro da lista: '))
  numeros.append(i)
  c += 1
print(f'A soma dos valores digitados é {sum(numeros)}')

In [ ]:
'''
Faça um programa que receba do usuário números inteiros e os insira na lista
somente se o número for ímpar e encerre o programa quando a lista tiver 5
números ímpares
'''
numeros = []
while len(numeros) < 5:
  n = int(input('Informe um número inteiro: '))
  if n % 2 != 0:
    numeros.append(n)
print(numeros)

In [ ]:
'''
Faça um programa que receba do usuário números inteiros e os insira na lista
somente se o número for ímpar e encerre o programa quando a lista tiver 5
números ímpares
'''
numeros = []
while len(numeros) < 5:
  n = int(input('Informe um número inteiro: '))
  if n % 2 != 0:
    numeros.append(n)
    #print(f'O número {n} é impar e foi inserido')
  #else:
    #print(f'O número {n} não é impar e não foi inserido')
print(numeros)

In [ ]:
'''
Faça um script que receba do usuário n números inteiros, armazene os
números recebidos a cada momento em que forem recebidos em uma lista e
no final exiba a soma desses valores. Considere que o usuário deverá informar
apenas 1 numero inteiro por caixa de diálogo é permitido usar (While)
'''
c = 0 # criei um contador para utilizar como parada do laço while
while True:
  try:
    n = int(input('Informe a qtde de números inteiros que deseja na lista: '))
    break
  except:
    pass
  print(f'''Cuidado! você não digitou um número inteiro, por favor faça isso''')
numeros = []
while c < n:
  try:
    i = int(input(f'Informe o {c+1}º número inteiro da lista: '))
    numeros.append(i)
    c += 1
  except:
    pass
    print(f'''Cuidado! você não digitou um número inteiro, por favor,
    digite o {c+1}º número nvamente''')
print(f'A soma dos valores digitados é {sum(numeros)}')

## **Funções**

In [ ]:
'''
def nomedafuncao (argumento 1, argumento 2, .... argumento n):
  bloco de código ou bloco de instruções
  return "valor"
'''

In [ ]:
# Exemplo de função sem argumento e sem bloco de código
def teste ():
  return print('Bom dia!')

In [ ]:
# Chamando a função teste criada no bloco anterior
teste()

In [ ]:
# Exemplo de função com argumento e com bloco de código
# crie uma função que receba dois argumentos (x, y) e faça o cálculo de x ** y
def casamento (x, y):
  vezes = x ** y
  return print(f'O professor douglas casará {vezes} vezes nessa vida')

In [ ]:
# chamando a função utilizando a ordem padrão dos argumentos
casamento(2, 3)

In [ ]:
# Chamando a função invertendo a ordem padrão dos argumentos sem aviso prévio (vai mudar o resultado anterior)
casamento(3, 2)

In [ ]:
# Para inverter a ordem padrão dos argumentos é necessário explicitar os valores dos argumentos
casamento(y=3, x=2)

In [ ]:
# Também é possível ser redundante e respeitar a ordem padrão dos argumentos e explicitar os seus valores
casamento(x=2, y=3)

In [ ]:
'''
Elabore uma função que receba do usuário os valores de preço de venda (p),
custo variável (cv), custo fixo (cf) e calcule o valor do ponto de equlíbrio
em quantidade e informe o usuário.
'''
def peq ():
  p = float(input('Informe o valor do preço unitário de venda em R$: '))
  cv = float(input('Informe o valor do custo variável unitário em R$: '))
  cf = float(input('Informe o valor do custo fixo mensal em R$: '))
  qt = cf/(p - cv)
  return print(f'A partir de aproximadamente {qt:.0f} unidades você terá lucro')

In [ ]:
peq()

Exercícios

In [ ]:
'''
Elabore uma função que receba em cinco inputs diferentes as seguintes informações:
1 - Receita líquida em R$
2 - Custo em R$
3 - Estoques em R$
4 - Contas a receber em R$
5 - Fornecedores em R$
6 - O Número de dias do balanço (int)

Após receber as informações acima a função deve calcular o valor e printá-lo dos
seguintes KPIs:

a Prazo médio de estoques - PME
b Prazo médio de Recebimento - PMR
c Prazo médio de Pagamento PMP
d Ciclo operacional - CO
e Ciclo de caixa

E por último:
Se PMP for maior que ciclo operacional print a mensagem essa em média empresa
paga tantos dias depois de receber

Se PMP for menor que ciclo operacional print a mensagem essa em média empresa
paga tantos dias antes de receber

Se PMP for igual ao ciclo operacional print a mensagem essa em média empresa
no mesmo dia em que recebe

PME = ESTOQUE / CUSTOS X Numero de dias do Balanço
PMR = Contas a receber do balanço / Receita Liquida X Numero de dias do Balanço
PMP = Fornecedores do balanço / Custos(pode ter uma diferença sendo compra) X Numero de dias do Balanço
C.O = PME + PMR
C.C = CO - PMP

'''

In [ ]:
'''def kpi():
  rl = float(input('Informe o valor da receita líquida em R$ '))
  c = float(input('Informe o valor do custo líquida em R$ '))
  e = float(input('Informe o valor do estoque em R$ '))
  cr = float(input('Informe o valor de contas a receber em R$ '))
  f = float(input('Informe o valor dos fornecedores em R$ '))
  dias = int(input('Informe o Número de dias do balanço '))

  pme = (e / c) * dias
  print(f'O Prazo médio de estoques é {pme:.0f} dias')
  pmr = (cr / rl) * dias
  print(f'Prazo médio de recebimentos é {pmr:.0f} dias')
  pmp = (f / c) * dias
  print(f'Prazo médio de pagamentos é {pmp:.0f} dias')
  co = pme + pmr
  print(f'Ciclo Operacional é {co:.0f} dias')
  cc = co - pmp
  print(f'Ciclo de Caixa é {cc:.0f} dias')
print(kpi())
#  if pmp > co:
#    print(f'essa em média empresa paga tantos dias antes de receber')'''

def giro ():
  receita = float(input('Informe a receita líquida em R$: '))
  custo = float(input('Informe o custo em R$: '))
  estoques = float(input('Informe o estoque em R$: '))
  ctas = float(input('Informe as contas a receber em R$: '))
  forne = float(input('Informe os fornecedores em R$: '))
  n = int(input('Informe o período do balanço em dias inteiros: '))
  pme = (estoques/custo)*n
  pmr = (ctas/receita)*n
  pmp = (forne/custo)*n
  co = pme + pmr
  cc = co - pmp
  print(f'O Prazo médio de estoques é  aproximadamente {pme:.0f} dias'),
  print(f'O Prazo médio de recebimento é  aproximadamente {pmr:.0f} dias'),
  print(f'O Prazo médio de pagamento é  aproximadamente {pmp:.0f} dias'),
  print(f'O ciclo operacional é  aproximadamente {co:.0f} dias'),
  print(f'O Ciclo de caixa é  aproximadamente {cc:.0f} dias')
  if pmp > co:
    print(f'Essa empresa em média paga {abs(cc):.0f} dias depois de receber')
  elif pmp < co:
    print(f'Essa empresa em média paga {abs(cc):.0f} dias antes de receber')
  else:
    print('Essa em média empresa no mesmo dia em que recebe')

giro()

In [ ]:
'''
Faça uma função sem parâmetro que ao ser acionada solicite ao usuário uma
sequência númerica em uma única caixa de texto e separada por espaços e então
após o usuário inserir os valores corretos a função devolva um print informando
o valor da média, da variância e do desvio padrão da sequência informada
'''
def describe ():
  dados = input('''Informe uma sequência de números (separados por espaços)
  que deseja calcular as medidas: ''')
  dados = dados.split()
  for i in range(len(dados)):
    dados[i] = float(dados[i])
  media = sum(dados)/len(dados)
  quad = []
  for i in range(len(dados)):
    quad.append((dados[i]-media)**2) # este bloco percorre cada valor da lista dados e calcula a diferença de cada um deles para a média, eleva ao quadrado e appenda na lista quad
  var = sum(quad)/(len(dados)-1)
  sd = var**(1/2)
  print(f'''As medidas descritivas são:
  média = {media:.2f},
  variância = {var:.2f} e
  desvio padrão = {sd:.2f}''')
describe()